### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/mine-cart-madness-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Basic C

- [ ] teleporter&#x2F;main.c dereferences the x value in the teleport function
- [ ] teleporter&#x2F;main.c dereferences the y value in the teleport function
- [ ] teleporter&#x2F;main.c dereferences the x parameter in the teleport function
- [ ] teleporter&#x2F;main.c dereferences the y parameter in the teleport function
- [ ] teleporter&#x2F;main.c passses values to teleport from main using the &#39;reference to&#39; operator
- [ ] teleporter&#x2F;main.c does not return values from the teleport function (no return statements)
- [ ] teleporter&#x2F;main.c classifies the teleport statement as a void return type, taking 2 parameters
- [x] passcode&#x2F;main.c crates passphrase using char array called code
- [x] passcode&#x2F;main.c creates passphrase using char array called code
- [ ] passcode&#x2F;main.c hide function accepts a dereferenced char pointer parameter
- [ ] passcode&#x2F;main.c hide function is typed as a char pointer
- [ ] passcode&#x2F;main.c hide function uses the strlen function to calculate char array size
- [ ] passcode&#x2F;main.c hide function uses malloc to allocate space for passcode string in heap
- [ ] passcode&#x2F;main.c hide function stores outcome of malloc as a char pointer
- [ ] passcode&#x2F;main.c hide function uses strcpy to move passcode local memory to malloc&#39;d memory
- [ ] passcode&#x2F;main.c hide function returns malloc&#39;d pointer value
- [ ] passcode&#x2F;main.c main function frees the malloc&#39;d heap memory for the char pointer
- [ ] cart-training&#x2F;main.c add_carts function typed as a pointer to a node struct, taking no parameters
- [ ] cart-training&#x2F;main.c creates a struct called &#39;node&#39; with int id and struct node *next
- [ ] cart-training&#x2F;main.c add_carts function malloc&#39;d at least 3 linked list node structs
- [ ] cart-training&#x2F;main.c add_carts function creates three NULL placeholders for linked list nodes
- [ ] cart-training&#x2F;main.c add_carts function uses -&gt; operator to populate pointer fields
- [ ] cart-training&#x2F;main.c main function uses a while loop to count the number of cars by finding NULL value

## TODO

- [ ] teleporter&#x2F;main.c contains no TODOs
- [ ] passcode&#x2F;main.c contains no TODOs
- [ ] cart-training&#x2F;main.c contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `7%` complete.
